minimum_pre_commit_version: "4.3.0"

# For `uv run pre-commit run --all-files`
exclude: "^(dist|site|.git|.venv|.pytest_cache|.ruff_cache|.mypy_cache)$"

repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.11
    hooks:
      - id: uv-lock

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        exclude: mkdocs.yml
      - id: forbid-new-submodules
      - id: name-tests-test
        args: [--pytest-test-first]
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: \.(json|svg|pot|po)$
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md,mdown,markdown"]
        exclude: \.(json|svg)$
      - id: fix-byte-order-marker

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        args:
          [
            "--disable=MD013",
            "--disable=MD029",
            "--disable=MD033",
            "--disable=MD041",
          ]

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-use-type-annotations

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.2.0
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
      - id: pyupgrade

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.8
    hooks:
      - id: ruff-check
        types_or: [python, pyi]
        args: [--fix, --show-fixes, --config=pyproject.toml]
      - id: ruff-format
        types_or: [python, pyi]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        args:
          [
            --ignore-missing-imports,
            --install-types,
            --non-interactive,
            --config-file=pyproject.toml,
          ]
        exclude: examples

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.33.2
    hooks:
      - id: check-github-workflows
        args: [--verbose]
      - id: check-dependabot
