name: Test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macOS-latest"]
        python-version: ["3.12", "3.13"]
        uv-version: ["latest"]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} Python ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: astral-sh/setup-uv@v6
        with:
          version: ${{ matrix.uv-version }}

      - name: Install dependencies of project
        run: uv sync --locked --no-group docs

      - name: Run checking of code
        run: uv run pre-commit run --show-diff-on-failure --color=always --all-files

      - name: Run tests
        run: uv run pytest -v tests/

  success:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: echo Test Successful
