name: Test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macOS-latest"] # "windows-latest",
        python-version: ["3.12", "3.13", "3.14"]
        uv-version: ["latest"]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} Python ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - uses: astral-sh/setup-uv@v6
        with:
          version: ${{ matrix.uv-version }}
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies with uv
        run: uv sync --locked --dev --group test

      - name: Install Pyrefly
        run: pip install pyrefly

      - uses: pre-commit/action@v3.0.1

      - name: Run tests
        run: |
          uv run pytest -v tests/test_utils.py
          uv run pytest -v tests/test_config.py
          uv run pytest -v tests/test_without_models.py
          uv run pytest -v tests/test_db.py
          uv run pytest -v tests/test_many_models.py
          uv run pytest -v tests/test_aggregation_classes.py
          uv run pytest -v tests/test_aggregation_average.py
          uv run pytest -v tests/test_aggregation_counter.py
          uv run pytest -v tests/test_aggregation_max.py
          uv run pytest -v tests/test_aggregation_min.py
          uv run pytest -v tests/test_aggregation_sum.py
          uv run pytest -v tests/test_cache.py
          uv run pytest -v tests/test_hash_reduce_left_0.py
